# Generated by Django 4.2.4 on 2023-08-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=20, null=True)),
                ('keywords', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link')),
                ('local', models.CharField(blank=True, max_length=250, null=True, verbose_name='LocalLink')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.category')),
            ],
            options={
                'ordering': ['-counter', '-id'],
            },
        ),
    ]
